### ISSUE TITLE
Screen Shots 

### ISSUE THREAD

**Issue by azubieta** [azubieta/KDE-AppImage-Thumbnailer#1]
![screenshot_20180324_160210](https://user-images.githubusercontent.com/1138094/37869431-0f0f3a52-2f7d-11e8-859a-7e02a00a8a6a.png)

**Comment by probonopd** [comment]
Looks good, but the shadowed box around the icons is annoying. Can you find a way in KDE Plasma to disable it?

**Comment by azubieta** [comment]
This feature would be better supported at https://github.com/azubieta/AppImageServices

Closing issue in order to archive the project.
