### ISSUE TITLE
Relation to KDE kio-extras

### ISSUE THREAD

**Issue by probonopd** [azubieta/KDE-AppImage-Thumbnailer#4]
Hi @azubieta, how does this relate to https://github.com/KDE/kio-extras/commit/e88a4c3d4a0233e33333f66236e69700719f6290?

Does https://phabricator.kde.org/D14998 mean that this repository is no longer used?

**Comment by azubieta** [comment]
It seems that they re-implement this functionality upstream.

**Comment by probonopd** [comment]
Can you tell whether both are functionally identical, or are there some aspects that should be contributed from this project to upstream? If they are functionally identical, is then still a reason to keep this one around? (I am trying to have _one_ tool for each job in AppImage, not _at least 2_ ;-) )

**Comment by azubieta** [comment]
Both are identical functionality wise. But they could use some improvements like generating the thumbnails from the icon with the same size if available.

Currently, to use the thumbnailer from the kde repo you have to build the whole repo. This is a bit more standalone and will serve as a backward compatible solution. It also will use some builds at the release page.

**Comment by azubieta** [comment]
This feature would be better supported at https://www.opencode.net/azubieta/plasma-appimage-integration/

Closing issue in order to archive the project.
