### ISSUE TITLE
Adapt thumbnailer for Deepin Desktop Environment?

### ISSUE THREAD

**Issue by probonopd** [azubieta/KDE-AppImage-Thumbnailer#5]
I wonder whether it would be possible to adapt this thumbnailer for the Deepin Desktop Environment, and how much work it would be. Deepin Desktop Environment is based on Qt.

https://github.com/linuxdeepin/dde-file-manager/tree/master/dde-file-manager-plugins/pluginPreview/dde-image-preview-plugin

From what we know, AppImage is really popular in China, where Deepin is from.

![](https://user-images.githubusercontent.com/2480569/49701550-c8381000-fbe5-11e8-857f-4551d29be333.png)

Source: Google Trends, AppImage, Worldwide, Past 12 months, Software

**Comment by azubieta** [comment]
This feature would be better supported at https://github.com/azubieta/AppImageServices

Closing issue in order to archive the project.
